export const CONTRACT_ADDRESS_MINTER = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_MINTER || '';


export const CONTRACT_ADDRESS_NFT_MINTER= process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_NFT_MINTER || '';

export const CONTRACT_ADDRESS_SOULBOUND_MINTER= process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_SOULBOUND_MINTER || '';